name: CI â†’ Build, Scan, Push to Docker Hub & Deploy


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello-simple


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'


      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q


      - name: Run Bandit (SAST)
        run: |
          bandit -r . || true


      - name: Run pip-audit (SCA)
        run: |
          pip-audit --output-format text || true


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image and tag latest + SHA
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} -t ${{ env.IMAGE_NAME }}:latest .


      - name: Scan Docker image with Trivy (run CLI)
        run: |
          docker pull aquasec/trivy:latest
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --format table ${{ env.IMAGE_NAME }}:${{ github.sha }} || true




      - name: Push image to Docker Hub (latest & sha)
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest


      # Optional deploy step (only runs on main branch)
      - name: Deploy to remote server via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker stop flask-hello || true
            docker rm flask-hello || true
           
            docker run -d --name flask-hello --restart unless-stopped -p 80:5000 ${{ env.IMAGE_NAME }}:latest
